package projection

import (
	"crypto/sha256"
	"embed"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"github.com/mash4649/atrakta/v0/internal/bindings"
	"github.com/mash4649/atrakta/v0/internal/onboarding"
	runpkg "github.com/mash4649/atrakta/v0/internal/run"
	resolvesurfaceportability "github.com/mash4649/atrakta/v0/resolvers/portability/resolve-surface-portability"
)

//go:embed templates/*.tmpl
var projectionTemplatesFS embed.FS

const DefaultTarget = resolvesurfaceportability.TargetAgentsMD
const generatedMarker = "This file is generated by `atrakta projection render`"

type targetSpec struct {
	TargetID   string
	TargetPath string
	Template   string
}

type templateData struct {
	ProjectRoot      string
	TargetID         string
	TargetPath       string
	CanonicalState   string
	InterfaceID      string
	InterfaceSource  string
	AssetLines       []string
	ContractLines    []string
	PortabilityLines []string
	Notes            []string
}

type Result struct {
	ProjectRoot      string                     `json:"project_root"`
	TargetPath       string                     `json:"target_path"`
	TargetID         string                     `json:"target_id,omitempty"`
	Interface        runpkg.InterfaceResolution `json:"interface"`
	CanonicalState   string                     `json:"canonical_state"`
	DetectedAssets   []string                   `json:"detected_assets"`
	SupportedTargets []string                   `json:"supported_targets,omitempty"`
	ExpectedHash     string                     `json:"expected_hash,omitempty"`
	ActualHash       string                     `json:"actual_hash,omitempty"`
	ProjectionStatus string                     `json:"projection_status,omitempty"`
	Drift            bool                       `json:"drift"`
	Written          bool                       `json:"written"`
	Message          string                     `json:"message"`
	Rendered         string                     `json:"-"`
}

func Render(projectRoot, targetPath, explicitInterface string) (Result, error) {
	root, err := onboarding.DetectProjectRoot(projectRoot)
	if err != nil {
		return Result{}, err
	}
	spec, err := resolveTargetSpec(root, targetPath)
	if err != nil {
		return Result{}, err
	}

	assets, err := onboarding.DetectAssets(root)
	if err != nil {
		return Result{}, err
	}
	sort.Strings(assets)
	assets = projectionAssetsForTarget(assets, spec.TargetPath)

	state, err := runpkg.DetectCanonicalState(root)
	if err != nil {
		return Result{}, err
	}
	if state == runpkg.StateNone {
		state = runpkg.StateNone
	}

	iface, err := runpkg.ResolveInterface(root, explicitInterface, "")
	if err != nil {
		if err == runpkg.ErrInterfaceUnresolved {
			iface = runpkg.InterfaceResolution{InterfaceID: "generic-cli", Source: "projection-default"}
		} else {
			return Result{}, err
		}
	}

	caps, err := bindings.Load(iface.InterfaceID)
	if err != nil {
		return Result{}, err
	}
	requested := requestedTargets(assets, caps)
	if !hasStringSlice(requested, spec.TargetID) {
		requested = append(requested, spec.TargetID)
	}
	portabilityInput := resolvesurfaceportability.Input{
		InterfaceID:         iface.InterfaceID,
		RequestedTargets:    requested,
		AvailableSources:    availableSources(assets, state != runpkg.StateNone),
		BindingCapabilities: caps,
		DegradePolicy:       resolvesurfaceportability.DegradePolicyProposalOnly,
	}
	portabilityOut := resolvesurfaceportability.ResolveSurfacePortability(portabilityInput)
	portabilityDecision, _ := portabilityOut.Decision.(resolvesurfaceportability.PortabilityDecision)

	rendered, err := renderDocument(root, spec, iface, state, assets, caps, portabilityDecision, portabilityOut.Reason)
	if err != nil {
		return Result{}, err
	}

	actual, err := os.ReadFile(spec.TargetPath)
	actualHash := ""
	projectionStatus := "missing"
	drift := true
	if err == nil {
		actualHash = hashBytes(actual)
		if string(actual) == rendered {
			projectionStatus = "up_to_date"
			drift = false
		} else if strings.Contains(string(actual), generatedMarker) {
			projectionStatus = "stale"
		} else {
			projectionStatus = "modified_externally"
		}
	} else if !os.IsNotExist(err) {
		return Result{}, err
	}

	return Result{
		ProjectRoot:      root,
		TargetPath:       filepath.ToSlash(spec.TargetPath),
		TargetID:         spec.TargetID,
		Interface:        iface,
		CanonicalState:   state,
		DetectedAssets:   assets,
		SupportedTargets: append([]string(nil), caps.ProjectionTargets...),
		ExpectedHash:     hashBytes([]byte(rendered)),
		ActualHash:       actualHash,
		ProjectionStatus: projectionStatus,
		Drift:            drift,
		Message:          "projection rendered",
		Rendered:         rendered,
	}, nil
}

func Write(projectRoot, targetPath, explicitInterface string) (Result, error) {
	res, err := Render(projectRoot, targetPath, explicitInterface)
	if err != nil {
		return Result{}, err
	}
	if err := writeRendered(res.TargetPath, res.Rendered); err != nil {
		return Result{}, err
	}
	res.Written = true
	res.Drift = false
	res.ProjectionStatus = "up_to_date"
	res.Message = "projection written"
	return res, nil
}

func Status(projectRoot, targetPath, explicitInterface string) (Result, error) {
	res, err := Render(projectRoot, targetPath, explicitInterface)
	if err != nil {
		return Result{}, err
	}
	res.Message = "projection status checked"
	return res, nil
}

func Repair(projectRoot, targetPath, explicitInterface string) (Result, error) {
	res, err := Render(projectRoot, targetPath, explicitInterface)
	if err != nil {
		return Result{}, err
	}
	if res.ProjectionStatus == "modified_externally" {
		res.Message = "projection repair blocked by externally modified target"
		return res, nil
	}
	if res.Drift {
		if err := writeRendered(res.TargetPath, res.Rendered); err != nil {
			return Result{}, err
		}
		res.Written = true
		res.ProjectionStatus = "up_to_date"
		res.Message = "projection repaired"
	} else {
		res.Message = "projection already in sync"
	}
	return res, nil
}

func writeRendered(targetPath, rendered string) error {
	if err := os.MkdirAll(filepath.Dir(targetPath), 0o755); err != nil {
		return err
	}
	return os.WriteFile(targetPath, []byte(rendered), 0o644)
}

func renderDocument(root string, spec targetSpec, iface runpkg.InterfaceResolution, state string, assets []string, caps resolvesurfaceportability.BindingCapabilities, portability resolvesurfaceportability.PortabilityDecision, reason string) (string, error) {
	contract, _ := runpkg.LoadMachineContract(root)
	data := templateData{
		ProjectRoot:      root,
		TargetID:         spec.TargetID,
		TargetPath:       filepath.ToSlash(spec.TargetPath),
		CanonicalState:   state,
		InterfaceID:      iface.InterfaceID,
		InterfaceSource:  iface.Source,
		AssetLines:       formatBullets(assets, "- ", "- (none detected)"),
		ContractLines:    summarizeContract(contract),
		PortabilityLines: formatPortabilityLines(portability, reason),
		Notes:            notesForTarget(spec.TargetID),
	}

	tmplName, err := templateNameForTarget(spec.TargetID)
	if err != nil {
		return "", err
	}
	tmplFile := tmplName + ".tmpl"
	tmpl, err := template.New(tmplFile).ParseFS(projectionTemplatesFS, "templates/"+tmplFile)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	if err := tmpl.ExecuteTemplate(&b, tmplFile, data); err != nil {
		return "", err
	}
	out := b.String()
	if !strings.HasSuffix(out, "\n") {
		out += "\n"
	}
	return out, nil
}

func notesForTarget(targetID string) []string {
	switch targetID {
	case resolvesurfaceportability.TargetIDERules:
		return []string{
			"- Projection is one-way. Edit source material, then rerender.",
			"- Use `atrakta projection status` to detect drift.",
			"- Use `atrakta projection repair` to restore the rendered file.",
		}
	case resolvesurfaceportability.TargetRepoDocs:
		return []string{
			"- Repo docs are advisory-only and generated from canonical guidance.",
			"- Use `atrakta projection status` to detect drift.",
			"- Use `atrakta projection repair` to restore the rendered file.",
		}
	case resolvesurfaceportability.TargetSkillBundle:
		return []string{
			"- Skill bundles are generated from canonical + skill assets.",
			"- Use `atrakta projection status` to detect drift.",
			"- Use `atrakta projection repair` to restore the rendered file.",
		}
	default:
		return []string{
			"- Projection is one-way. Edit source material, then rerender.",
			"- Use `atrakta projection status` to detect drift.",
			"- Use `atrakta projection repair` to restore the rendered file.",
		}
	}
}

func formatBullets(values []string, prefix, empty string) []string {
	if len(values) == 0 {
		return []string{empty}
	}
	out := make([]string, 0, len(values))
	for _, value := range values {
		out = append(out, prefix+value)
	}
	return out
}

func formatPortabilityLines(portability resolvesurfaceportability.PortabilityDecision, reason string) []string {
	lines := []string{
		"- status: `" + portability.PortabilityStatus + "`",
		"- reason: `" + reason + "`",
	}
	if len(portability.ProjectionPlan) > 0 {
		lines = append(lines, "- supported targets:")
		for _, item := range portability.ProjectionPlan {
			line := "  - " + item.RequestedTarget
			if item.EffectiveTarget != "" && item.EffectiveTarget != item.RequestedTarget {
				line += " -> " + item.EffectiveTarget
			}
			line += " (`" + item.Status + "`)"
			lines = append(lines, line)
		}
		return lines
	}
	return append(lines, "- supported targets: (none)")
}

func templateNameForTarget(targetID string) (string, error) {
	switch targetID {
	case resolvesurfaceportability.TargetAgentsMD:
		return "agents_md", nil
	case resolvesurfaceportability.TargetIDERules:
		return "ide_rules", nil
	case resolvesurfaceportability.TargetRepoDocs:
		return "repo_docs", nil
	case resolvesurfaceportability.TargetSkillBundle:
		return "skill_bundle", nil
	default:
		return "", fmt.Errorf("unsupported projection target %q", targetID)
	}
}

func resolveTargetSpec(root, target string) (targetSpec, error) {
	targetID := normalizeTargetID(target)
	if targetID == "" {
		targetID = DefaultTarget
	}
	switch targetID {
	case resolvesurfaceportability.TargetAgentsMD:
		return targetSpec{TargetID: targetID, TargetPath: filepath.Join(root, "AGENTS.md"), Template: "agents_md"}, nil
	case resolvesurfaceportability.TargetIDERules:
		return targetSpec{TargetID: targetID, TargetPath: filepath.Join(root, ".cursor", "rules", "atrakta.md"), Template: "ide_rules"}, nil
	case resolvesurfaceportability.TargetRepoDocs:
		return targetSpec{TargetID: targetID, TargetPath: filepath.Join(root, "docs", "generated", "atrakta.md"), Template: "repo_docs"}, nil
	case resolvesurfaceportability.TargetSkillBundle:
		return targetSpec{TargetID: targetID, TargetPath: filepath.Join(root, "skills", "generated", "atrakta-skill-bundle.md"), Template: "skill_bundle"}, nil
	default:
		return targetSpec{}, fmt.Errorf("unsupported projection target %q", target)
	}
}

func normalizeTargetID(target string) string {
	target = strings.TrimSpace(strings.ToLower(target))
	target = strings.TrimPrefix(target, "./")
	target = filepath.ToSlash(target)
	switch {
	case target == "", target == "agents_md", target == "agents.md", strings.HasSuffix(target, "/agents.md"):
		return resolvesurfaceportability.TargetAgentsMD
	case target == "ide_rules", strings.Contains(target, ".cursor/rules"):
		return resolvesurfaceportability.TargetIDERules
	case target == "repo_docs", strings.Contains(target, "docs/"):
		return resolvesurfaceportability.TargetRepoDocs
	case target == "skill_bundle", strings.Contains(target, "skills/"):
		return resolvesurfaceportability.TargetSkillBundle
	default:
		return target
	}
}

func summarizeContract(contract map[string]any) []string {
	if len(contract) == 0 {
		return []string{"- (missing or invalid contract)"}
	}

	lines := []string{}
	if v, ok := contract["project_id"].(string); ok && strings.TrimSpace(v) != "" {
		lines = append(lines, "- project_id: `"+v+"`")
	}
	if v, ok := contract["v"]; ok {
		lines = append(lines, "- version: `"+fmt.Sprint(v)+"`")
	}
	if iface, ok := contract["interfaces"].(map[string]any); ok {
		if supported, ok := iface["supported"].([]any); ok && len(supported) > 0 {
			items := make([]string, 0, len(supported))
			for _, item := range supported {
				items = append(items, fmt.Sprint(item))
			}
			sort.Strings(items)
			lines = append(lines, "- supported_interfaces: `"+strings.Join(items, ", ")+"`")
		}
		if fallback, ok := iface["fallback"].(string); ok && strings.TrimSpace(fallback) != "" {
			lines = append(lines, "- fallback_interface: `"+fallback+"`")
		}
	}
	if boundary, ok := contract["boundary"].(map[string]any); ok {
		if managed, ok := boundary["managed_root"].(string); ok && managed != "" {
			lines = append(lines, "- managed_root: `"+managed+"`")
		}
	}
	if tools, ok := contract["tools"].(map[string]any); ok {
		if allow, ok := tools["allow"].([]any); ok && len(allow) > 0 {
			items := make([]string, 0, len(allow))
			for _, item := range allow {
				items = append(items, fmt.Sprint(item))
			}
			sort.Strings(items)
			lines = append(lines, "- tools_allow: `"+strings.Join(items, ", ")+"`")
		}
	}
	if len(lines) == 0 {
		lines = append(lines, "- (empty contract)")
	}
	return lines
}

func requestedTargets(assets []string, caps resolvesurfaceportability.BindingCapabilities) []string {
	assetSet := make(map[string]struct{}, len(assets))
	for _, asset := range assets {
		assetSet[asset] = struct{}{}
	}
	targets := []string{}
	if hasAsset(assetSet, "AGENTS.md") && supportsTarget(caps, resolvesurfaceportability.TargetAgentsMD) {
		targets = append(targets, resolvesurfaceportability.TargetAgentsMD)
	}
	if hasAsset(assetSet, ".cursor", ".cursor/rules", ".vscode") && supportsTarget(caps, resolvesurfaceportability.TargetIDERules) {
		targets = append(targets, resolvesurfaceportability.TargetIDERules)
	}
	if hasAsset(assetSet, "docs") && supportsTarget(caps, resolvesurfaceportability.TargetRepoDocs) {
		targets = append(targets, resolvesurfaceportability.TargetRepoDocs)
	}
	if supportsTarget(caps, resolvesurfaceportability.TargetSkillBundle) && hasAsset(assetSet, "skills", ".codex/skills") {
		targets = append(targets, resolvesurfaceportability.TargetSkillBundle)
	}
	if len(targets) == 0 && supportsTarget(caps, resolvesurfaceportability.TargetAgentsMD) {
		targets = append(targets, resolvesurfaceportability.TargetAgentsMD)
	}
	return unique(targets)
}

func availableSources(assets []string, canonicalPresent bool) []string {
	assetSet := make(map[string]struct{}, len(assets))
	for _, asset := range assets {
		assetSet[asset] = struct{}{}
	}
	sources := []string{}
	if canonicalPresent {
		sources = append(sources, resolvesurfaceportability.SourceCanonicalPolicy)
	}
	if hasAsset(assetSet, ".cursor", ".cursor/rules", ".vscode") {
		sources = append(sources, resolvesurfaceportability.SourceIDERules)
	}
	if hasAsset(assetSet, "docs") {
		sources = append(sources, resolvesurfaceportability.SourceRepoDocs)
	}
	if hasAsset(assetSet, "AGENTS.md") {
		sources = append(sources, resolvesurfaceportability.SourceAgentsMD)
	}
	if hasAsset(assetSet, "skills", ".codex/skills") {
		sources = append(sources, resolvesurfaceportability.SourceSkillAsset)
	}
	return unique(sources)
}

func supportsTarget(caps resolvesurfaceportability.BindingCapabilities, target string) bool {
	for _, item := range caps.ProjectionTargets {
		if strings.EqualFold(item, target) {
			return true
		}
	}
	return false
}

func hasAsset(set map[string]struct{}, names ...string) bool {
	for _, name := range names {
		if _, ok := set[name]; ok {
			return true
		}
	}
	return false
}

func hasStringSlice(values []string, target string) bool {
	for _, value := range values {
		if strings.EqualFold(value, target) {
			return true
		}
	}
	return false
}

func projectionAssetsForTarget(assets []string, targetPath string) []string {
	if targetPath == "" {
		return append([]string(nil), assets...)
	}
	targetBase := filepath.Base(targetPath)
	if targetBase == "" {
		return append([]string(nil), assets...)
	}
	out := make([]string, 0, len(assets))
	for _, asset := range assets {
		if filepath.Base(asset) == targetBase {
			continue
		}
		out = append(out, asset)
	}
	return out
}

func unique(items []string) []string {
	seen := map[string]struct{}{}
	out := make([]string, 0, len(items))
	for _, item := range items {
		if _, ok := seen[item]; ok {
			continue
		}
		seen[item] = struct{}{}
		out = append(out, item)
	}
	return out
}

func normalizeTargetPath(root, target string) string {
	target = strings.TrimSpace(target)
	if target == "" {
		return ""
	}
	if filepath.IsAbs(target) {
		return target
	}
	return filepath.Join(root, filepath.FromSlash(target))
}

func hashBytes(b []byte) string {
	sum := sha256.Sum256(b)
	return hex.EncodeToString(sum[:])
}
